language: node_js
cache:
  directories:
    - $HOME/.npm
node_js:
  - lts/*

stages:
  - test
  - name: release
    if: branch = master AND type IN (push)

jobs:
  include:
    - stage: test
      script: npm run test:ci
    - stage: release
      script: npm run semantic-release
      deploy:
        script: scripts/deploy.sh
        provider: script
        skip_cleanup: true
