name: Publish and release

on: [push]

env: 
  PROJECT_ID: 1053850952252
jobs:
  build-and-test:
    name: Build and test code
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm build
        npm run test:ci
      env: 
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  sonarcloud-scan:
    name: Sonarcloud scan      
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
  release-and-deploy:
    name: Release to NPM registry and deploy to 
    needs: [build-and-test, sonarcloud-scan]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  
    steps:
    - uses: actions/checkout@v1
    - name: npm install
      run: npm install
    - name: publish
      run: npm run semantic-release
      env: 
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: setup gcloud connection
      run: |
        mkdir ~/.gcloud
        echo $GCP_TOKEN >> ~/.gcloud/keyfile.json
      env: 
        GCP_TOKEN: ${{ secrets.GCP_ACCOUNT_KEY }}
    - name: deploy to gcloud
      run: |
        node_modules/serverless/bin/serverless.js deploy -v

